# Base configs
baseurl: "https://github.com/bizmoz/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"


# UI configs
title: "Photography"
subtitle: "world through my eyes!"
author: "RP"
header:
 title: "Photography"
 subtitle: "by Bizmoz"
footer:
 name: "Hey there, my name is Bizmoz"
 bio: "I am a developer and a tech."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/bizmoz/photography\">fork me on github</a> ;)"
web_design: "Bizmoz"
social_urls:
  facebook: "https://www.facebook.com/"
  twitter: "https://www.twitter.com/"
  instagram: "https://www.instagram.com/"
  dribbble: "https://dribbble.com/"
  linkedin: "https://in.linkedin.com/"
  github: "https://www.github.com/"
